server:
  port: 8071
spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/configs,classpath:/configs/{application},classpath:/configs/common,classpath:/configs/{application}/{profile}"
  logging:
    level:
      root: DEBUG

